

# zsh extensions
brew 'zsh-you-should-use'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'zsh-vi-mode'

# symlink manager
brew 'stow'

# terminal QOL
brew 'gum'
brew 'eza'
brew 'zoxide'
brew 'ripgrep'
brew 'fzf'
brew 'starship'
brew 'bat'

# vim
brew 'neovim'

# git
brew "git"
tap 'jesseduffield/lazygit'
brew "jesseduffield/lazygit/lazygit" # git tui



