#!/usr/bin/env zsh

export TERM=xterm-256color

###########
# ALIASES #
###########
alias vim=nvim
alias v=nvim



####################
# SHELL TOOL SETUP #
####################

# < eza >
alias ls=eza
export EZA_ICONS_AUTO=1


# < starship >
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
eval "$(starship init zsh)"

# < zoxide >
eval "$(zoxide init zsh)"

# < zsh plugins >
local BREW_PREFIX="$(brew --prefix)"
for script in \
    "zsh-autosuggestions/zsh-autosuggestions.zsh" \
    "zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" \
    "zsh-you-should-use/you-should-use.plugin.zsh" \
    "zsh-vi-mode/zsh-vi-mode.plugin.zsh"
do
    source "${BREW_PREFIX}/share/${script}"
done


alias youtube-mp4='yt-dlp -f bestvideo+bestaudio --merge-output-format mov -v'

