#!/usr/bin/env zsh

eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by Toolbox App
export PATH="$PATH:${HOME}/Library/Application Support/JetBrains/Toolbox/scripts"

export PATH="${HOME}/.local/bin:$PATH"

# uv
export PATH="${XDG_DATA_HOME}/../bin:$PATH"

# go
export PATH="$(go env GOPATH)/bin:$PATH"

export PATH="~/.local/bin:$PATH"

# bun install -g
export PATH="/Users/stoli/.local/cache/.bun/bin:$PATH"

export PATH="$PATH:/Users/stoli/.mix/escripts"

export OLLAMA_HOST="http://127.0.0.1:42069"
